project:
  type: website
  output-dir: docs

website:
  title: "insights-diary"
  favicon: images/favicon.jpg
  open-graph: true
  google-analytics: "G-274QZTFL23"
  comments: 
    hypothesis:
      theme: clean
      openSidebar: true
  navbar:
    right:
      - text: About
        href: about.qmd
      - icon: house
        href: https://remi-theriault.com/
      - icon: github
        href: https://github.com/rempsyc/
      
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css

editor: visual

